### ISSUE TITLE
Not assign readonly variable PRODUCT_SYSTEM_DEFAULT_PROPERTIES

### ISSUE THREAD

**Issue by FalconJaw** [Wave-Project/vendor_wave#5]
In compiling in eng or usedebug builds have this error in line 32 vendor/wave/configs/props.mk:32: error: cannot assign to readonly variable: PRODUCT_SYSTEM_DEFAULT_PROPERTIES

**Comment by adithya2306** [comment]
will you resync? I've already force pushed the fix few hours ago
